### PR TITLE
Bundler-2.4 requires Ruby 2.6 or later

### PR DESCRIPTION
**Pull request by hsbt**
Resolved https://github.com/ruby/setup-ruby/issues/422

### CODE REVIEW

**Comment by MSP-Greg** [comment]
Thanks for a PR on Christmas Eve (Happy Holidays/Merry Christmas!)

Not my call, but...

 I think it would be better to force install of RG 3.2.3 (which correctly handles `required_ruby_version`), rather than force a bundler version?  I think that can be done such that it leaves RUby 2.6 and later alone.  I think I can do that quickly...

**Comment by MSP-Greg** [comment]
Thanks for a PR on Christmas Eve (Happy Holidays/Merry Christmas!)

Not my call, but...

 I think it would be better to force install of RG 3.2.3 (which correctly handles `required_ruby_version`), rather than force a bundler version?  I think that can be done such that it leaves RUby 2.6 and later alone.  I think I can do that quickly...

**Review by eregon — APPROVED** [review]
Thank you for the PR!

**Comment by hsbt** [comment]
Hi Greg, Eregon, Happy Holidays and Thanks for all your works for Ruby.

>Would it be better to force install of RG 3.2.3 (which correctly handles required_ruby_version), rather than force a bundler version?

It's not needed yet. Because RubyGems is internally usage different with Bundler by Ruby users.

**Comment by eregon** [comment]
@MSP-Greg That would choose the same Bundler version, but also update RubyGems which users unlikely have done locally to the same version + a more risky change

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby/releases/tag/v1.129.0

**Pull request merged**
