### PR TITLE
Upstream supported dev dependency versions

### PR DESCRIPTION
**Pull request by benlangfeld**

### CODE REVIEW

**Comment by eregon** [comment]
As mentioned in https://github.com/ruby/setup-ruby/pull/592#discussion_r1590278937 we should instead remove those files (and add tests creating these files dynamically ideally, right now these files are unused), could you update the PR to do that?

**Comment by benlangfeld** [comment]
These files are very much used in the local environment of a developer working on this project. I do not think dynamically generating them for CI is at all related to the concern this PR fixes.

**Comment by eregon** [comment]
That's not their purpose in this project, e.g. see https://github.com/ruby/setup-ruby/commits/master/.ruby-version https://github.com/ruby/setup-ruby/commits/master/.tool-versions
They were only added for testing, but probably these tests got removed.

There is no need for any particular version of these tools to work on this project, it's JS anyway.

**Comment by benlangfeld** [comment]
> There is no need for any particular version of these tools to work on this project, it's JS anyway.

There is no need for any particular version of these tools to work on this project, it's JS anyway.

NodeJS and Yarn are required. Is it not preferable for these to be readily available to contributors via a dependency management solution (this or Docker, for example) than to require their manual installation/selection?

**Comment by eregon** [comment]
Look, I know why I added them, the versions there are meant to test setup-ruby picking the ruby version from it, nothing else.
And I do not want to bother updating these or get noise in PRs from them.

**Pull request closed without merging**
