### PR TITLE
Remove bundler enforcement on ruby 2.3

### PR DESCRIPTION
**Pull request by bpinto**
The fix for rubygems/rubygems#3570 was released with bundler 2.2.0.rc.1.

### CODE REVIEW

**Comment by eregon** [comment]
Related: https://github.com/ruby/setup-ruby/issues/128

I guess the reason for the change is you want to use Bundler 2 on Ruby 2.3?
Seems reasonable now that that bug is fixed, but I would not be too surprised if there are other issues with Bundler on Ruby 2.3.

You need to update the generated files as mentioned in CONTRIBUTING.md.

**Comment by bpinto** [comment]
> I guess the reason for the change is you want to use Bundler 2 on Ruby 2.3?

You are correct. 👍 

> You need to update the generated files as mentioned in CONTRIBUTING.md.

Sorry, I read that when I was creating the PR and after running `npm run package` I forgot to push the updated commit 😓

**Review by eregon — APPROVED** [review]
Thanks for the PR

**Comment by eregon** [comment]
Released as https://github.com/ruby/setup-ruby/releases/tag/v1.64.0

**Pull request merged**
