### PR TITLE
Add JRuby 9.2.13.0

### PR DESCRIPTION
**Pull request by greghuc**
dist/index.js has changed more than I expected..

### CODE REVIEW

**Comment by eregon** [comment]
I started the build of JRuby 9.2.13.0 in https://github.com/ruby/ruby-builder/actions/runs/204454881

**Comment by eregon** [comment]
Can you try `yarn install` and `yarn check` and post what it gives?
The lint job fails, showing it is most likely is some issue in your environment.
It looks like it's using some newer version of some package.

**Comment by greghuc** [comment]
So I realised that I used npm - not yarn. I've just run "yarn run package", and re-uploaded dist/index.js. That looks much better

**Comment by greghuc** [comment]
```
yarn install
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 4.59s.

yarn check
yarn check v1.22.4
success Folder in sync.
```

**Comment by greghuc** [comment]
```
yarn run lint
yarn run v1.22.4
$ eslint *.js
/bin/sh: eslint: command not found
error Command failed with exit code 127.
```

So lint is failing as I somehow don't have eslint installed

**Comment by greghuc** [comment]
All checks now pass - yay!

**Comment by eregon** [comment]
Yes, I removed eslint as it depended on so many packages which regularly have vulnerabilities, and it was not very useful. I'll remove the command too.

Thanks for the PR!

**Comment by eregon** [comment]
https://github.com/ruby/setup-ruby/releases/tag/v1.41.0

**Pull request merged**
