### PR TITLE
Add JRuby 9.2.11.0

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Not exactly sure what the process for adding new rubies is, I just "copied" 7f508b5101e9cc2d7cbb7851689507771d9ff6c6.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I see by the failures that this building this ruby needs to be triggered by a push to https://github.com/ruby/ruby-builder, right?

**Comment by MSP-Greg** [comment]
Yes.  This repo just handles the download & installing in the Action runner.

As you mentioned, ruby-builder is where all the binaries are built and stored, except for head/master builds & Windows MRI builds...  (I think)

**Comment by eregon** [comment]
Yep, that's documented in https://github.com/ruby/setup-ruby#supported-platforms.
I'll trigger the build in ruby-builder.

**Comment by eregon** [comment]
Merged, released, v1 updated.

**Comment by deivid-rodriguez** [comment]
Thanks!

**Pull request merged**
