### PR TITLE
Use the Bundler shipped with that Ruby by default

### PR DESCRIPTION
**Pull request by eregon**
* Fixes https://github.com/ruby/setup-ruby/issues/358

### CODE REVIEW

**Comment by eregon** [comment]
Something that may be surprising is this results in (if there is no Gemfile.lock):
* Ruby < 2.3: installs latest Bundler 1 (Bundler 2 needs Ruby 2.3+)
* Ruby 2.3 - 2.5: installs latest Bundler 2
* Ruby 2.6: uses default gem Bundler 1 (previously: installs latest Bundler 2)
* Ruby 2.7+: uses default gem Bundler 2

**Comment by dentarg** [comment]
Someone might argue that this change should require a major version bump of the action. I can empathize with that seeing the fallout at https://github.com/ruby/setup-ruby/issues/358#issuecomment-1195899304, but I see your are tweaking this (https://github.com/ruby/setup-ruby/pull/363) so we might be okay in the end?

**Comment by dentarg** [comment]
I understand why we want to avoid major bumps, it's a lot of churn for many where the change might not matter. There's also not nice to cut of all v1 users from future updates, that's probably the main argument.

**Comment by eregon** [comment]
Yes, I thought a bit about a v2.
I think in general I want something that is compatible enough, hence a v2 is not really needed.

And if that was v2 then we'd get in a situation where:
* Few people use v2, and annoying lots of users to update for almost no reason
* Many people use v1 but I have no time to maintain more than 1 branch or backport things to it. We'd get lots of issues about v1 which is wasting time.

So a v2 seems a bad trade-off to me.
If it turns out too incompatible, we can revert this change entirely.

**Pull request merged**
