### PR TITLE
`README.md`: Mention link to supported Ruby versions for GitHub-hosted runners

### PR DESCRIPTION
**Pull request by stdedos**
Fixes https://github.com/ruby/setup-ruby/issues/650

Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>

### CODE REVIEW

**Review by eregon — APPROVED** [review]
Thanks

**Comment by stdedos** [comment]
> Thanks

... I would appreciate a heads up before merging 😕

I won't try to source an "very authoritative source", but `[here]()` urls can be a very bad thing to do from a11y point-of-view, e.g. https://heyoka.medium.com/dont-use-click-here-f32f445d1021#a1f6

**Comment by eregon** [comment]
The entire README has no URLs as plain text, because that takes a very large amount of space and IMO hurts readability. So I did the obvious fix, keeping your sentence as-is, and I undid the unrelated whitespace changes which are intentional.

Feel free to propose a better wording or linking.

**Comment by stdedos** [comment]
> and I undid the unrelated whitespace changes (the spaces are intentional and have an effect).

Those changes were _unintentional_ from my part. All of my smart editors are configured to prune trailing whitespace.

What effect do they have on Github Commonmark? 😕

Note that https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#paragraphs mentions

>You can create a new paragraph by leaving a blank line between lines of text.

and there is a testament of the GhFM-feature on the internet: https://stackoverflow.com/a/24576087/2309247

It is mentioned in https://github.github.com/gfm/#hard-line-break, https://docs.gitlab.com/ee/user/markdown.html#newlines for ways to force a line break (including the N>1 trailing spaces) - but even if https://stackoverflow.com/a/24576087/2309247 is not mentioned, it still happens.
See this comment for example. 😅

**Comment by eregon** [comment]
It forces a newline, without extra vertical spacing, as e.g. in https://github.com/ruby/setup-ruby?tab=readme-ov-file#caching-bundle-install-automatically
It doesn't affect comments but it does affect the README.

**Pull request merged**
