### PR TITLE
Update for JRuby 9.2.17.0

### PR DESCRIPTION
**Pull request by headius**

### CODE REVIEW

**Comment by headius** [comment]
What is the proper procedure for updating versions? I tried the `pre-commit` script but that seemed to break index.js. Editing index.js directly with my editor appears to replace all newlines with unix-style (are they windows style normally?)

**Comment by headius** [comment]
Redid the commit by editing files manually in vim, to avoid regenerating badly or replacing newlines.

**Comment by eregon** [comment]
@headius JRuby 9.2.17 seems to have some issue on Windows, see
https://github.com/ruby/setup-ruby/pull/165/checks?check_run_id=2227889407
```
$ gem install sassc -N
Successfully installed ffi-1.15.0-java
Building native extensions. This could take a while...
ERROR:  Error installing sassc:
	ERROR: Failed to build gem native extension.

    current directory: D:/jruby-9.2.17.0/lib/ruby/gems/shared/gems/sassc-2.4.0/ext
D:/jruby-9.2.17.0/bin/jruby.exe -I D:/jruby-9.2.17.0/lib/ruby/stdlib -r ./siteconf20210330-2584-1pgoh9i.rb extconf.rb
extconf failedNo such file or directory - {"SOURCE_DATE_EPOCH"=>"1617110021"}

Gem files will remain installed in D:/jruby-9.2.17.0/lib/ruby/gems/shared/gems/sassc-2.4.0 for inspection.
Results logged to D:/jruby-9.2.17.0/lib/ruby/gems/shared/extensions/universal-java-1.8/2.5.0/sassc-2.4.0/gem_make.out
```

And it worked fine on 9.2.16 2 days ago in https://github.com/ruby/setup-ruby/runs/2212961109

**Comment by tedhexaflow** [comment]
Hi @headius @eregon 

Would this version be released soon?

Thanks 🙏

**Comment by eregon** [comment]
I filed a JRuby issue about this failure: https://github.com/jruby/jruby/issues/6648
Given that installing sassc on JRuby on Windows is probably something most users won't do, and they can pin to 9.2.16.0 if needed, I'll merge this.
I'll need to exclude that test on JRuby to keep the CI green then.

**Comment by eregon** [comment]
@tedhexaflow released now.

**Comment by tedhexaflow** [comment]
Thank you so much 🙏🙏

**Pull request merged**
