### PR TITLE
windows.js - use proper case for ENV['Path']

### PR DESCRIPTION
**Pull request by MSP-Greg**
Both locally and on Actions, the case used is 'Path'

### CODE REVIEW

**Comment by eregon** [comment]
Looks good. Is this the standard case on Windows? From what I remember env variables are case insensitive on Windows, right?

**Comment by MSP-Greg** [comment]
> From what I remember env variables are case insensitive on Windows, right?

In theory.  But, one may have issues if one is dumping ENV to an object/hash.  Also made worse by the fact that Windows allows both '/' and '\\' for path separators...

I hate this.  I was just thinking of opening an issue in one of the GitHub Actions repos.

I also have a point of reference that is biased by the needs of building and testing ruby master, where having only one Ruby in PATH is helpful for CI.

So, I'm not sure whether this PR should be merged or whether we should remove the code below, which makes sure that only one Ruby install is in PATH:
```
core.exportVariable('Path', newPath)
```

I was working on setup-ruby-pkgs, and wondered if using `core.exportVariable('Path', str1)` and also `core.addPath(str2)`, both here and possibly in subsequent actions could be a little unstable?

**Comment by MSP-Greg** [comment]
The above msg is a little general.

Things got a little squirrely when I had a `core.exportVariable('Path', str1)` command in setup-ruby-pkgs, which may have overwritten the `core.exportVariable` and/or `core.addPath` commands used in setup-ruby.

So, I think ``core.exportVariable('Path', str1)`` commands should not be used.  Thoughts?

JFYI, the issue that I had in ruby-setup-pkgs was a conflict with the multitude of build tools in 'Path' on the Actions Windows images.  I had to rename a 'gmake.exe' file...

**Comment by MSP-Greg** [comment]
I'm working on another PR

**Comment by eregon** [comment]
I'm OK to merge this FWIW

**Comment by MSP-Greg** [comment]
I hope that PR https://github.com/ruby/setup-ruby/pull/32 supersedes this?

**Comment by eregon** [comment]
Let's close this since #32 was merged.
We can use the proper name on Windows in `index.js`'s `setupPath()`, please make a new PR if you want that.

**Pull request closed without merging**
