### PR TITLE
Add option to disable deployment mode

### PR DESCRIPTION
**Pull request by Pandapip1**
Pretty self-explanatory. My use-case is that I am developing on a windows machine but that the GitHub action is running on a Linux machine.

### CODE REVIEW

**Comment by dentarg** [comment]
Linking with past discussion about deployment mode: https://github.com/ruby/setup-ruby/issues/292 (see https://github.com/ruby/setup-ruby/issues/292#issuecomment-1050924495 for a workaround)

Also sounds like you should be able to use deployment mode if you add Linux as a platform? (And there's work in progress for Bundler making this easier (despite the title of the now draft-PR) https://github.com/rubygems/rubygems/pull/5700)

**Comment by Pandapip1** [comment]
The thing is, the gemfile *isn't* out of sync and installs fine with no changes.

**Comment by dentarg** [comment]
Sounds like a Bundler bug? Can you share the specifics so other can reproduce?

**Comment by Pandapip1** [comment]
I can point you to a commit: https://github.com/ethereum/EIPs/tree/17b8bf36950848eca4482f3488b4ccc5ea130b8a

**Comment by MSP-Greg** [comment]
There are a lot of Bundler config options.  Obviously, adding even a small number of them to this action's inputs would be a PITA.

Most can be set via ENV variables.

At present, setup-ruby is setting the following:
```
bundle config --local deployment true
```

Maybe a better solution is to set it to the equivalent of `ENV.fetch('BUNDLE_DEPLOYMENT', 'true')`?

Update the README to discuss setting Bundler options via ENV, and mention the default value for BUNDLE_DEPLOYMENT?

As to the PR from ethereum/EIPs, see https://github.com/ethereum/EIPs/pull/5383

@Pandapip1 I would be very careful pinning Actions to a particular commit, as in:
```
actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
ruby/setup-ruby@08245253a76fa4d1e459b7809579c62bd9eb718a
```

**Comment by Pandapip1** [comment]
> Maybe a better solution is to set it to the equivalent of ENV.fetch('BUNDLE_DEPLOYMENT', 'true')?

I would be happy with that.

> I would be very careful pinning Actions to a particular commit, as in:

The reason we are doing so is to protect against supply chain attacks.

**Comment by MSP-Greg** [comment]
> to protect against supply chain attacks

And you're using `ruby-version: 2.6.0`?

**Comment by eregon** [comment]
https://github.com/ethereum/EIPs/runs/7599734447?check_suite_focus=true
```
 You are trying to install in deployment mode after changing
  your Gemfile. Run `bundle install` elsewhere and add the
  updated Gemfile.lock to version control.
  
  If this is a development machine, remove the /home/runner/work/EIPs/EIPs/Gemfile
  freeze
  by running `bundle config unset deployment`.
  
  You have deleted from the Gemfile:
  * wdm (~> 0.1.0)
```
So clearly they are out of sync (or it could be a Bundler bug maybe).
Either way, that tell me the default is good, and make people investigate what they do wrong with the Gemfile/Gemfile.lock.
Disabling this would more or less be the same as not having a lockfile.

**Comment by eregon** [comment]
Yes, looking if `BUNDLE_DEPLOYMENT=false` could be one way, but so far I have yet to see a valid use case for it, in my experience it reveals important issues with Gemfile.lock and there is no need to disable it.

**Pull request closed without merging**
