### PR TITLE
Add JRuby 9.2.18.0

### PR DESCRIPTION
**Pull request by walro**

### CODE REVIEW

**Comment by eregon** [comment]
JRuby 9.2.18.0 needs to first be added to https://github.com/rbenv/ruby-build first,
then I can add it to https://github.com/ruby/ruby-builder and then merge this.

**Comment by walro** [comment]
Ah, TIL! I will see if I can get to that today too then :)

**Comment by hsbt** [comment]
I added 9.2.18.0 definition to ruby-build at https://github.com/rbenv/ruby-build/pull/1772

**Comment by eregon** [comment]
Thanks for the PR.
`jruby-head` is failing, which is tracked as https://github.com/ruby/setup-ruby/issues/186

**Comment by eregon** [comment]
Released in https://github.com/ruby/setup-ruby/releases/tag/v1.73.0

**Pull request merged**
